### ISSUE TITLE
The Mysql.Data 6.10.6 version does not support DataSet, and if the return type is DataSet, the error is reported.

### ISSUE THREAD

**Issue by ghd258** [Chavoshi/EnterpriseLibrary.NetCore#10]
The Mysql.Data 6.10.6 version does not support DataSet, and if the return type is DataSet, the error is reported.

**Comment by Chavoshi** [comment]
Can you please open your problem?
How can I reproduce the issue?

**Comment by ghd258** [comment]
It should be that MySql.Data 6.10.6 does not implement the return to DataSet
