### ISSUE TITLE
Can you replace Oracle 's Connector/NET. () with MySqlConnector ()?

### ISSUE THREAD

**Issue by ghd258** [Chavoshi/EnterpriseLibrary.NetCore#17]
Can you replace Oracle 's Connector/NET. (https://github.com/mysql/mysql-connector-net) with MySqlConnector (https://github.com/mysql-net/MySqlConnector)?

**Comment by Chavoshi** [comment]
Why should we change the Oracle Connector with MySql Connector?

**Comment by ghd258** [comment]
I've given up using Enterprise Library, and I'm using SmartSql for database access (https://github.com/Ahoo-Wang/SmartSql), so I suggest you look at this as well.
