### ISSUE TITLE
App/Web.config configuration replacement

### ISSUE THREAD

**Issue by Courela** [Chavoshi/EnterpriseLibrary.NetCore#18]
Hi,
I'm migrating an application that uses Enterprise Library (cache mechanism) from dotNet Framework to dotNet Core. In dotNet Framework I have some configuration in App/Web.config to set cache managers and backing stores. How does it works now with .Net Core? All my research pointed out to having a json file read with a ConfigurationBuilder. If this is the way how do I pass the configuration read from json file to "Cache factory classes"?

Thanks

**Comment by Chavoshi** [comment]
Just create an app.config file in your .Net Core 2.0 project and your configuration will be processed as before.
There is sample [here](https://github.com/Chavoshi/EnterpriseLibrary.NetCore/tree/master/Examples/EnterpriseLibrary.Test.MySql) for Data Application block which you can follow and replicate it for the Caching application block as well.
