### ISSUE TITLE
Are there plans to Strong Name these assemblies?

### ISSUE THREAD

**Issue by StingyJack** [Chavoshi/EnterpriseLibrary.NetCore#21]
Trying to do a 1:1 replacement with the existing EL doesn't exactly work as these are not strong named.

**Comment by Chavoshi** [comment]
Where do you have issue?
In the configuration or somewhere else?

**Comment by StingyJack** [comment]
I have several hundred assemblies and programs that are all strong named that use the original net framework Enterprise Library.  So if I try to replace that version of Enterprise Library with this one, it does not work and I get compile errors because these are not strong named like the original ones. 

I was able to get around this problem temporarily by cloning this repository, adding an SNK to the projects I need (data, common), then making a new package for them and pushing it to our private nuget repo.

**Comment by StingyJack** [comment]
THank you, that answers my question.
