### ISSUE TITLE
EnterpriseLibrary official seems to have stopped updating. Are you ready to extend support for SQL Server 2014, SQL Server 2016, or SQL Server 2017?

### ISSUE THREAD

**Issue by ghd258** [Chavoshi/EnterpriseLibrary.NetCore#3]
EnterpriseLibrary official seems to have stopped updating. Are you ready to extend support for SQL Server 2014, SQL Server 2016, or SQL Server 2017?

**Comment by Chavoshi** [comment]
Honestly, I didn't get you, What do you mean by supporting SQL Server 2014, 2016, and 2017?
Because just now we are using EntLib with a wide range of application using SQL Server 2008, 2012, 2014 and 2016 and they are working very smoothly.
Can you please expand your request?

**Comment by ghd258** [comment]
The main question is whether the SQL Server 2014 or 2016 and 2017 are the same as SqlDbType

**Comment by Chavoshi** [comment]
The way that you are asking the question shows you couldn't completely understand the philosophy of the Enterprise Library Data Application Block which is just a wrapper to your DB Provider.
For example when you use **SqlDatabase**, it uses the normal **SqlClientFactory, SQLCommand, SqlDbType, And etc**, which are defined in **System.Data.Common**.

In fact, Enterprise Library Data Application Block has noting to do with the version of SQL Server or any other DB Providers.
