### ISSUE TITLE
Porting remaining 5.0 blocks?

### ISSUE THREAD

**Issue by memark** [Chavoshi/EnterpriseLibrary.NetCore#32]
I'm currently using EntLib 5.0, including _Data_ block and _Caching_ block. Moving to .NET Core I found your wonderful ports of EntLib!

However, I can only find ports of _Data_ 6.0 och _Caching_ 5.0, which don't really seem to work together (more explicitly, they expect different versions of _Common_).

And I know _Caching_ was removed in 6.0. Are there any plans to port the remaining 5.0 blocks?

Or do you have any other ideas how to port this _Data_/_Caching_ block application?

**Comment by Chavoshi** [comment]
In fact the Caching and Cryptography blocks which are ported, are using the **Common v.6.0**, so feel free to use them together with **Data v.6.0**.

**Comment by memark** [comment]
That is excellent, will try right away! Thanks for the information.
