### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by niteshgaba** [Chavoshi/EnterpriseLibrary.NetCore#4]
Hi,

Could you please share the documentation or the sample code of storing the connection string in applicationsettings.json?

Regards 
Nitesh

**Comment by Chavoshi** [comment]
Since config section support is added to .Net Core 2.0, you can add your connections strings into your application configuration file.

Take a look at this thread:
https://github.com/Chavoshi/EnterpriseLibrary.NetCore/issues/2
