### ISSUE TITLE
I experienced this issue in version 2.0 but once 3.1 came and then 6 it was gone

### ISSUE THREAD

**Issue by HenryWolfe** [Chavoshi/EnterpriseLibrary.NetCore#6]
Cannot implicitly convert microsoft.practices.enterpriselibrary.data.database to Microsoft.Practices.EnterpriseLibrary.Data.Sql.SqlDatabase an explicit converson exists

**Comment by Chavoshi** [comment]
Really sorry for the delay as I was really busy with some project.
Honestly I've got your problem. Can you open your problem please.
Do you still have this issue?
