### ISSUE TITLE
How this package can be usable ?

### ISSUE THREAD

**Issue by wadinj** [Chavoshi/EnterpriseLibrary.NetCore#8]
Hello,

I'm trying to migrate a project from .NET Framework to .NET Core. I notice that this package user ConfigurationManager from System.Configuration which is no longer usable in .NET CORE 2.

Per example, if I call `DatabaseProviderFactory.Create(string name)`, this method will call `(ConfigurationSection)ConfigurationManager.GetSection(s)`.

How are you able to use this package ?

Thanks,
Jonathan

**Comment by Chavoshi** [comment]
Sorry for the delay.
Can you please open your problem?

If you are looking for a sample project you can find it here: https://github.com/Chavoshi/EnterpriseLibrary.NetCore/tree/master/Examples/EnterpriseLibrary.Test.MySql
